### ISSUE TITLE
[Macro Context] Driving questions

### ISSUE THREAD

**Issue by blasrodri** [blasrodri/vc_proposal#5]
Let's create a set of **questions** that we have as guidelines for when we'll start pulling out the data that will point us to the answers.

### Startups

1. Volume of deals in quantity and $ yearly in the last years by stage
2. Number of startups per industry
3. Number that are having cashflow, and how many are past breakeven.
4. Markets to which they export. Can we get detailed figures on that? 

### Investors

1. Number of investors and stage in which they are
2. Number of deals they invest in yearly
3. Stages they invest in
4. Industries in which they invest 
5. Number of investments made outside of the country where they are based - interconnectivity?

**Comment by matirebozov** [comment]
Blas, regarding what you posted: i transcribed your questions mixing them with the ones i thought. 
Few doubts: 
Startups:
3. When you refer to cashflow and past breakeven, isn't it given by the stage or not necessary? Anyway, that information is not in our database.
4. We can't get detailed figures on this. However, maybe it is possible by going to the startup website. We have to think about that.
5. The interconnectivity of investors, or region diversification has to be checked manually looking to the detail of fundings done by each investor. The information is available. Maybe we can do it only for the most representative investors per region.
Please take a look on the new branch (editing-macro-context) and pull if you agree.

**Comment by blasrodri** [comment]
Can you please clarify how to answer to these questions?

A. What kind of structure is mainly used for investing? // Is it legal structure?

B. Are investors aligned with the markets and industries entrepreneurs are targeting? // How do you measure alignment?

C. Are Startups income diversified per region? In what sense?

**Comment by matirebozov** [comment]
First of all, do you agree these are the main questions to answer?

A. Investors are classified by type: Accelerator, VC, Micro VC, Angel, etc. On the other hand, we can check what kind of funding has startups received and then get to a conclusion per region. After confirming this information we can ask more accurately to contacts or do online research more precisely for the LEGAL STRUCTURE.

B. We can see which are the markets and industries where entrepreneurs are choosing to develop. After this and by picking the main investors per region, we can take a deeper look to their portfolio and manually see if their representative portfolios are aligned or not to what startups are doing.

C. Manually by looking to the investors portfolio's we can see in which regions they are investing. However, i don't have a clear idea of how to measure the income diversification per region for each startups (if they sell abroad apart from local markets) except going one by one checking thousands of websites and sending emails.

**Comment by blasrodri** [comment]
I cannot see how to clearly answer the alignment between the market and startups. How do we define that? 

And diversification could be in one/several dimensions. I am more interested in geographic diversification, since it talks about the product + team capabilities of competing globally.

**Comment by matirebozov** [comment]
I will try to be more clear: 

B.

1. From our database we can check startup growth from the last years per industry. With this information we can check, in each country, which is the area/market this startups are choosing to develop. 
2. We can pick the top 3 investors per region and check:
a. Their investment strategy.
b. Their porfolios (information available in our databse).

Is 2. consistent with 1.'s trend? Still, we can leave this for the last part of our proposal, but i believe it's a very interesting point to decide where to target our investment policies.

C. 

With "income diversified per region" i meant to check if startups are selling products/services to their own countries only or abroad too. This is not possible to see from out database.

**Comment by blasrodri** [comment]
Great. 

B1. OK
B2. Would represent the main focus of the investors in the region. This does not mean that startups do not want to do something else. Maybe it is just that investors are not lending for anything different. But we can get a picture of where is the money flowing towards.

I don't think that is possible that B1 and B2 are not consistent. The startups need money. The question to me is more: Is the market missing any global trend? Should **we** focus on anything particular that has not been fully exploded?

C. OK

If you agree, add it and close the issue.

**Comment by matirebozov** [comment]
I agree with you. I will replace the question for the one you suggested.

**Comment by blasrodri** [comment]
Great job!
