### ISSUE TITLE
Comments regarding the DB Investors file

### ISSUE THREAD

**Issue by blasrodri** [blasrodri/vc_proposal#7]
## Concentration of type of investors

Is it in numbers of investments? We should use money instead. Because by definition an angel invests in more deals than a VC, since they pour less money on each deal but diversify in many more companies instead. 
**Compare using $$ among investor types.**

## Summary

I think we can get a good overview of the industry with this. We are still missing really interesting data about the startups to complete it. I will send you my file with a few more insights, which I hope you find them relevant to include these figures.

**Comment by blasrodri** [comment]
@matirebozov Do you have any insights to share on this topic? Otherwise I can close it.

**Comment by matirebozov** [comment]
@blasrodri many thanks for the comments. I do agree with you regarding the concentration per investors in terms of money. It would give a better view of the ecosystem. However, our database is not providing this information.

**Comment by matirebozov** [comment]
Nonetheless, startups section is showing fundings amounts and type of fundings. Maybe we can get useful information from there. I'm working with that now.

**Comment by matirebozov** [comment]
The figures you did include in the investors file i found them very usefull for our analysis. Thanks.
